### ISSUE TITLE
unused dependencies

### ISSUE THREAD

**Issue by cvan** [simplecampus/hapi-pg#5]
I don't see where these dependencies are used.

##### [`dependencies`](https://github.com/simplecampus/hapi-pg/blob/6fd1535/package.json#L22)
* `"pgpass": "0.0.2"`

##### [`devDependencies`](https://github.com/simplecampus/hapi-pg/blob/6fd1535/package.json#L26)
* `"mocha": ">1.16.2"`

and why is `hapi` in both [`devDependencies`](https://github.com/simplecampus/hapi-pg/blob/6fd1535/package.json#L25) and [`peerDependencies`](https://github.com/simplecampus/hapi-pg/blob/6fd1535/package.json#L29)?

**Comment by Adamanthil** [comment]
These should be cleaned up via 250e7b6be7aff712d38b4eac902d3331f31bdc68 and published in version 1.0.0
